### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by Affannnn** [mjmeans/Appx-Backup#1]
please provide the appx file of wreck it ralph, thanks

**Comment by mjmeans** [comment]
I  won't distribute any app unless I own the distribution rights. So even if I had a copy of that app, I wouldn't commit software piracy by providing it to anyone. The only way you can legally possess that app is if you  had download it personally from the Microsoft Store when it was available. It is no longer available, so anyone who it and who hasn't made a backup is screwed. This project allows you to make a backup of a single app instead of having to backup an entire machine. But you have to have the app in the first place.

**Comment by Affannnn** [comment]
You can distribute it. Its a free app. Like the apk files are still avalible for it but I want it back on my pc. Even apk files for paid apps are avalible, even thousands of xep files are avalible. There is no problem, you can send it to me.

**Comment by mjmeans** [comment]
No I can't. You need to study the law. The copyright holder retains all rights and enters contracts with a distributor (such as Microsoft Store) for distribution under whatever terms are agreed to. Any customer of that distributor is still governed by the terms of distribution to the end user as specified in the end user license agreement. No other distributor can provide the work unless they have also contracted with the copyright owner regardless of the cost or lack of cost to an end user. Specifically, if an end user acquired the work from one distributor (whether paid or not), it doesn't grant that end user the right to receive the work from any other licensed distributor without cost. And, even if the original distributor provided it for free, that doesn't make the work public domain and able to be freely distributed by anyone. Only the copyright holder can release a work as public domain.

So if you ever had downloaded it form Microsoft Store, and you need to re-download it, your only recourse is to find another distributor and possibly pay for it again, or receive it from Microsoft Store. In the case of the wreck it ralph app, I don't believe even Microsoft has retained the right and responsibility to provide it to you unless you actually paid money for it.

If you acquire any non-public domain app from anyone other than a properly licensed distributor, you and the distributor are comitting a crime. Free at one time doesn't mean free forever; only "public domain" does.
