### ISSUE TITLE
Cert prompts

### ISSUE THREAD

**Issue by wrecklesswun** [mjmeans/Appx-Backup#10]
Anyway to make it so the password is a variable, vs the constant popups?  I'm trying to repair a vital virtual machine.

**Comment by mjmeans** [comment]
MakeCert doesn't have any parameter that accepts a password. [docs](https://docs.microsoft.com/en-us/windows/win32/seccrypto/makecert) I'm assuming this is by design for security reasons.

I don't know of any other MS provided tool that could replace MakeCert that can also satisfy this project's use case. There might be, I just haven't seen it.

You could roll your own application that interfaces to the Windows crpyto API and use that on your own by replacing the calls to MakeCert to your own code. But I won't support that, and any such code could not be merged into this project.

This project must be pristine and use MS provided tools only so that it can't be legitimately argued that this is some kind of hacking tool. There was a time, long ago, that this repo was suspended pending a review to make sure it wasn't considered a hacking tool. I need to keep all appearances away that this might be somehow construed by meritless and demagogic claims of hacking. So, this project will never use or support ways to circumvent MS provided tools except in the rare case where it's being replaced with another MS provided tool.

**Comment by wrecklesswun** [comment]
sounds good.  just thought i'd ask if it could be passed.
